// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将覆盖对此文件的更改。
// </auto-generated>
// ------------------------------------------------------------------------------

namespace UsageTracker
{
    using System;
    
    /// <summary>
    /// 命令表中定义的命令ID的标识符
    /// </summary>
    internal static class CommandIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int cmdidShowUsageStats = 0x0100;
    }
    
    /// <summary>
    /// 命令表中使用的GUID的标识符
    /// </summary>
    internal static class PackageGuids
    {
        public const string guidPackageString = "d5a0d2e1-9c9b-4f5a-9a1c-3b8e7e9f4d7a";
        public static readonly Guid guidPackage = new Guid(guidPackageString);
        public static readonly Guid guidCommandSet = new Guid("d5a0d2e1-9c9b-4f5a-9a1c-3b8e7e9f4d7a");
    }
} 